# Generated by Django 5.0.7 on 2024-08-07 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0009_delete_historicalsociete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_util', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.site')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_interne', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('date_invtaire', models.DateField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.categorie')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.site')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.utilisateur')),
            ],
        ),
    ]
