# Generated by Django 5.0.7 on 2024-08-08 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('adresse1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ville')),
                ('region', models.CharField(choices=[('MA01', 'Tanger-Tétouan-Al Hoceïma'), ('MA02', "L'Oriental"), ('MA03', 'Fès-Meknès'), ('MA04', 'Rabat-Salé-Kénitra'), ('MA05', 'Béni Mellal-Khénifra'), ('MA06', 'Casablanca-Settat'), ('MA07', 'Marrakech-Safi'), ('MA08', 'Drâa-Tafilalet'), ('MA09', 'Souss-Massa'), ('MA10', 'Guelmim-Oued Noun'), ('MA11', 'Laâyoune-Sakia El Hamra'), ('MA12', 'Dakhla-Oued Ed-Dahab'), ('ATRE', 'Autre / Etranger')], max_length=6, verbose_name='Région')),
            ],
        ),
        migrations.RemoveField(
            model_name='produit',
            name='site',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='site',
        ),
        migrations.AddField(
            model_name='categorie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
