# Generated by Django 5.0.7 on 2024-08-08 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_site_remove_produit_site_remove_utilisateur_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.site'),
            preserve_default=False,
        ),
    ]
