# Generated by Django 5.0.7 on 2024-08-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_produit_site_utilisateur_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='date_invtaire',
            new_name='date_inventaire',
        ),
    ]
