# Generated by Django 5.0.7 on 2024-08-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_rename_date_invtaire_produit_date_inventaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='service',
        ),
    ]
