# Generated by Django 5.0.7 on 2024-08-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_utilisateur_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code_interne',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
