# Generated by Django 5.0.7 on 2024-08-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_produit_code_interne'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='produits',
            field=models.ManyToManyField(related_name='categories', to='stock.produit'),
        ),
    ]
