# Generated by Django 5.0.7 on 2024-08-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_remove_categorie_produits'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_achat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='etat',
            field=models.CharField(choices=[('en_service', 'En service'), ('en_stock', 'En stock'), ('en_cours_de_maintenance', 'En cours de maintenance'), ('hors_service', 'Hors service')], default='en_stock', max_length=50),
        ),
        migrations.AddField(
            model_name='produit',
            name='valeur_achat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
