# Generated by Django 4.2.3 on 2024-07-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_historicalperimeter_category_history_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsociete',
            name='hht_logo',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='hht_logo',
        ),
    ]
