# Generated by Django 4.2.3 on 2024-07-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_historicalsociete_hht_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsite',
            name='enable_odometer_checks',
        ),
        migrations.RemoveField(
            model_name='historicalsite',
            name='enbale_lifo_loading',
        ),
        migrations.RemoveField(
            model_name='site',
            name='enable_odometer_checks',
        ),
        migrations.RemoveField(
            model_name='site',
            name='enbale_lifo_loading',
        ),
    ]
