# Generated by Django 4.2.3 on 2024-07-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_historicalsite_enable_odometer_checks_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
