# Generated by Django 4.2.3 on 2024-07-24 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalSociete',
            new_name='HistoricalSocietee',
        ),
        migrations.RenameModel(
            old_name='Societe',
            new_name='Societee',
        ),
        migrations.AlterModelOptions(
            name='historicalsocietee',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical societee', 'verbose_name_plural': 'historical Sociétés'},
        ),
    ]
