# Generated by Django 4.2.3 on 2024-07-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_historicalsocietee_historicalsociete_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSociete',
        ),
    ]
